### ISSUE TITLE
Xenko 3.1 Cannot resolve paths with spaces.

### ISSUE THREAD

**Issue by FailMelon** [xenko3d/xenko#385]
**Release Type**: Official Release/GitHub (please choose appropriate option)
Official Release - Beta

**Version**: Version number and/or git branch
3.1.0.1-beta01-0441

**Platform(s)**: Does the problem occur on Windows, Android...?
Windows 10

**Describe the bug**
When creating a new project xenko cannot find files it needs, i believe this is caused because there is a space in my windows user.

**To Reproduce**
1. Create a windows account with a space
2. Try to create a project under 3.1 build.

**Expected behavior**
Xenko should be able to resolve paths with spaces.

**Screenshots**
If applicable, add screenshots to help explain your problem (use GitHub drag & drop)
![image](https://user-images.githubusercontent.com/3711395/52957370-5f3be980-3346-11e9-941e-24e413a2dbc1.png)

**Comment by tebjan** [comment]
sounds like this was already fixed in latest master, just not yet published as new beta: https://github.com/xenko3d/xenko/pull/381

**Comment by FailMelon** [comment]
Ah i missed this pull request that would probably fix it.

**Comment by tebjan** [comment]
let's hope for a new beta soon then.

**Comment by Kryptos-FR** [comment]
@tebjan I don't think #381 will do anything for that issue.

And in general having spaces in username is bad and I expect other software to break as well. Looking on the Internet (in your favourite search engine) with a search query such as "Windows username space" brings a lot of results with various software, program or tools failing.

**Comment by FailMelon** [comment]
@Kryptos-FR I'm not even gonna begin to start at how ignorant that post is, if #381 doesn't fix it then it needs to be resolved still.

**Comment by Kryptos-FR** [comment]
@failmelon I'm not even gonna begin to start how disrespectful your post was. #381 was fixing a different issue, regarding building the sources.

**Comment by xen2** [comment]
@FailMelon Thanks for the report.

This specific issue you had is an issue in the T4 template generator lib we use.
I have pushed a fix for it already: 4372725f93

Please wait for the next beta release.
